<?php /* @var $this Fooman_PdfCustomiser_Block_Pdf_Items*/?>
<?php $columnHeadings = $this->getColumnHeaders() ?>
<?php $pdfItems = $this->getItems() ?>
<?php $pdfBundleItems = $this->getBundleItems() ?>
<?php $maxColumns = sizeof($columnHeadings) ?>
<?php $position = 1 ?>
<?php $vertSpacing =
    '<tcpdf method="addHTMLVertSpace" params="'.$this->getPdf()->serializeTCPDFtagParameters(array(1, 3)).'"/>'
?>

<?php $lineStyleOverride = array(
    'style_first'=> 'border-top:1px solid red;',
    'style_last'=> 'border-bottom:1px solid red;',
    'horiz_whitespace'=>5
) ?>
<?php $lineStyleOverride = false ?>
<?php
if($this->getPdfHelper()->getOrder()->getStartDatetime()){
    $start_date = ITwebexperts_Payperrentals_Helper_Date::localiseNonsequentialBuyRequest($this->getPdfHelper()->getOrder()->getStartDatetime(),true);
}
if($this->getPdfHelper()->getOrder()->getEndDatetime()) {
    $end_date = ITwebexperts_Payperrentals_Helper_Date::localiseNonsequentialBuyRequest($this->getPdfHelper()->getOrder()->getEndDatetime(), true);
}
if($this->getPdfHelper()->getOrder()->getSendDatetime()) {
    $send_date = ITwebexperts_Payperrentals_Helper_Date::localiseNonsequentialBuyRequest($this->getPdfHelper()->getOrder()->getSendDatetime(), true);
}
if($this->getPdfHelper()->getOrder()->getReturnDatetime()) {
    $return_date = ITwebexperts_Payperrentals_Helper_Date::localiseNonsequentialBuyRequest($this->getPdfHelper()->getOrder()->getReturnDatetime(), true);
}
?>
<?php if($this->getPdfHelper()->getOrder()->getStartDatetime()):?>
    <table width="35%" border="0" cellpadding="2" cellspacing="0">
        <tr>
           <td><strong><?php echo $this->__('Rental Start Date:')?></strong></td><td><?php echo $start_date ?></td>
        </tr>
        <tr>
           <td><strong><?php echo $this->__('Rental End Date:')?></strong></td><td><?php echo $this->getPdfHelper()->getOrder()->getEndDatetime()?$end_date:'' ?></td>
        </tr>
        <tr>
           <td><strong><?php echo $this->__('Dropoff Date:')?></strong></td><td><?php echo $this->getPdfHelper()->getOrder()->getSendDatetime()?$send_date: $this->__('To Be Confirmed') ?></td>
        </tr>
        <tr>
           <td><strong><?php echo $this->__('Pickup Date:')?></strong></td><td><?php echo $this->getPdfHelper()->getOrder()->getReturnDatetime()?$return_date: $this->__('To Be Confirmed') ?></td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
    </table>
<?php endif;?>
<?php $numColumns = count($columnHeadings) ?>
<?php if($columnHeadings): ?>
    <table width="100%" border="0" cellpadding="2" cellspacing="0">
        <thead>
            <tr nobr="true">
                <?php foreach ($columnHeadings as $columnHeading) :?>
                    <th style="<?php echo $numColumns==count($columnHeadings)?'border-left: 2px solid #808080; ':'' ?>
                    <?php echo $numColumns==1?'border-right: 2px solid #808080; ':'' ?> background-color: #ededed; font-weight:bold; border-bottom: 2px solid #808080; border-top: 2px solid #808080; "
                        align="<?php echo $columnHeading['align'] ?>"
                        width="<?php echo $columnHeading['width'] ?>%"><p style="line-height:0.8cm">&nbsp;<strong><?php echo $columnHeading['title'] ?></strong>&nbsp;&nbsp;</p></th>
                        <?php $numColumns--?>
                <?php endforeach;?>
            </tr>
        </thead>
        <?php foreach ($pdfItems as $pdfItem) :?>
            <!-- we generally do not want to display subitems of configurable products etc -->
            <?php if($pdfItem['parentItemId']) continue; ?>
            <!-- Output line items -->
            <?php if (($pdfItem['parentType'] != 'bundle' && $pdfItem['type'] != 'bundle')
                || ($pdfItem['type'] == 'bundle' && !isset($pdfBundleItems[$pdfItem['itemId']]))) :
            ?>
                <tr nobr="true">
                    <?php echo $this->getItemRow($pdfItem, $vertSpacing, $lineStyleOverride, $position++) ?>
                </tr>
            <!-- Deal with bundles -->
            <?php else: ?>
                <?php $currentParentId = $pdfItem['itemId'] ?>
                <tr nobr="true">
                    <?php echo $this->getBundleItemRow($pdfItem, $pdfBundleItems[$currentParentId], $vertSpacing, $lineStyleOverride, $position++) ?>
                </tr>
            <?php endif; ?>
        <?php endforeach;?>
    </table>
<?php endif; ?>
